# Generated by Django 3.1.5 on 2021-01-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pettify_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pettify_crm.address'),
        ),
    ]
